# Generated by Django 3.2.3 on 2021-05-28 23:38

from django.conf import settings
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(post.models.get_sentinel_user), to='auth.user', verbose_name='Yazar'),
            preserve_default=False,
        ),
    ]
